### ISSUE TITLE
Something wrong with video size?

### ISSUE THREAD

**Issue by JennaSmu** [azzhu/EasyFlyTracker#1]
I'm on an HP computer and I'm having trouble getting the tracking done. I set up the config.yaml correctly, and I can get the video up to put point A + B there but the video is a weird size and it's huge. But, I can see enough to put my A + B points and put the red circle where I want. Then, the program collects frames put it doesn't move onto the tracking step, giving me an error message instead. It says: 
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\HP\OneDrive\Wartburg\NSC 455\venv\Scripts\easyFlyTracker.exe\__main__.py", line 7, in <module>
  File "C:\Users\HP\OneDrive\Wartburg\NSC 455\venv\lib\site-packages\easyFlyTracker\cli.py", line 35, in easyFlyTracker_
    f = FlySeg(**params)
  File "C:\Users\HP\OneDrive\Wartburg\NSC 455\venv\lib\site-packages\easyFlyTracker\src_code\fly_seg.py", line 105, in __init__
    self.comp_bg()
  File "C:\Users\HP\OneDrive\Wartburg\NSC 455\venv\lib\site-packages\easyFlyTracker\src_code\fly_seg.py", line 172, in comp_bg
    frames = np.array(frames)
numpy.core._exceptions._ArrayMemoryError: Unable to allocate 4.63 GiB for an array with shape (800, 1920, 1080, 3) and data type uint8

I'm not into computer science and have no previous experience with python so I don't know what the problem is here. It looks like something is wrong with the video file size? I've tried compressing the video. The original file was at 228,417 KB and then I compressed it to 130,710 KB. That still didn't work so I compressed it again to 72,948 KB but I still get this error message. I don't know what is wrong. 

Another one of my groupmates got easyFlyTracker to work on her computer and it works great there! So I think this is a good tool, but it is hard to get it to work right, and you don't have many troubleshooting tips on your site. We had trouble getting python to recognize easyFlyTracker though we eventually figured it out. So, any tips on how to solve this would be greatly appreciated.

**Comment by azzhu** [comment]
There should be a memory overflow. How much is your computer memory? You can check the computer memory information and see if the memory is full when easyflytracker is running. Good luck.

**Comment by azzhu** [comment]
> There should be a memory overflow. How much is your computer memory? You can check the computer memory information and see if the memory is full when easyflytracker is running. Good luck.

There should be a memory overflow. How much is your computer memory? You can check the computer memory information and see if the memory is full when easyflytracker is running. Good luck.

**Comment by azzhu** [comment]
> 

There should be a memory overflow. How much is your computer memory? You can check the computer memory information and see if the memory is full when easyflytracker is running. Good luck.

**Comment by azzhu** [comment]
> I'm on an HP computer and I'm having trouble getting the tracking done. I set up the config.yaml correctly, and I can get the video up to put point A + B there but the video is a weird size and it's huge. But, I can see enough to put my A + B points and put the red circle where I want. Then, the program collects frames put it doesn't move onto the tracking step, giving me an error message instead. It says: Traceback (most recent call last): File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 196, in _run_module_as_main return _run_code(code, main_globals, None, File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.752.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 86, in _run_code exec(code, run_globals) File "C:\Users\HP\OneDrive\Wartburg\NSC 455\venv\Scripts\easyFlyTracker.exe__main__.py", line 7, in File "C:\Users\HP\OneDrive\Wartburg\NSC 455\venv\lib\site-packages\easyFlyTracker\cli.py", line 35, in easyFlyTracker_ f = FlySeg(**params) File "C:\Users\HP\OneDrive\Wartburg\NSC 455\venv\lib\site-packages\easyFlyTracker\src_code\fly_seg.py", line 105, in **init** self.comp_bg() File "C:\Users\HP\OneDrive\Wartburg\NSC 455\venv\lib\site-packages\easyFlyTracker\src_code\fly_seg.py", line 172, in comp_bg frames = np.array(frames) numpy.core._exceptions._ArrayMemoryError: Unable to allocate 4.63 GiB for an array with shape (800, 1920, 1080, 3) and data type uint8
> 
> I'm not into computer science and have no previous experience with python so I don't know what the problem is here. It looks like something is wrong with the video file size? I've tried compressing the video. The original file was at 228,417 KB and then I compressed it to 130,710 KB. That still didn't work so I compressed it again to 72,948 KB but I still get this error message. I don't know what is wrong.
> 
> Another one of my groupmates got easyFlyTracker to work on her computer and it works great there! So I think this is a good tool, but it is hard to get it to work right, and you don't have many troubleshooting tips on your site. We had trouble getting python to recognize easyFlyTracker though we eventually figured it out. So, any tips on how to solve this would be greatly appreciated.

There should be a memory overflow. How much is your computer memory? You can check the computer memory information and see if the memory is full when easyflytracker is running. Good luck.
