### ISSUE TITLE
cv2 error, fly_seg

### ISSUE THREAD

**Issue by DrinkAstragalus** [azzhu/EasyFlyTracker#10]
Hi, I met an error recently when the program calculated background image:
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\huang\micromamba\envs\mpy\Scripts\easyFlyTracker.exe\__main__.py", line 7, in <module>
  File "C:\Users\huang\micromamba\envs\mpy\Lib\site-packages\easyFlyTracker\cli.py", line 50, in easyFlyTracker_
    f = FlySeg(**params_filter)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\huang\micromamba\envs\mpy\Lib\site-packages\easyFlyTracker\src_code\fly_seg.py", line 123, in __init__
    self.comp_bg()
  File "C:\Users\huang\micromamba\envs\mpy\Lib\site-packages\easyFlyTracker\src_code\fly_seg.py", line 286, in comp_bg
    self.gray_bg_int16 = cv2.cvtColor(bg, cv2.COLOR_BGR2GRAY).astype(np.int16)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.8.1) d:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\color.simd_helpers.hpp:92: error: (-2:Unspecified error) in function '__cdecl cv::impl::`anonymous-namespace'::CvtHelper<struct cv::impl::`anonymous namespace'::Set<3,4,-1>,struct cv::impl::A0xd8611878::Set<1,-1,-1>,struct cv::impl::A0xd8611878::Set<0,2,5>,3>::CvtHelper(const class cv::_InputArray &,const class cv::_OutputArray &,int)'
> Invalid number of channels in input image:
>     'VScn::contains(scn)'
> where
>     'scn' is 1

It seems there is an error of color channels.

**Comment by DrinkAstragalus** [comment]
It should be 
`bg = sx[0]`
in line 278 in fly_seg.py,
as 'keepdims' is set to false by default in stats.mode in SciPy v1.11.3.

**Comment by azzhu** [comment]
Thank you for your feedback!

**Comment by azzhu** [comment]
Thank you for your feedback! This issue has been fixed, you can update easyFlyTracker and use it:
pip install --upgrade easyFlyTrakcer 
Thanks.
