### ISSUE TITLE
The software cannot take input video in my case

### ISSUE THREAD

**Issue by jasmin1008** [azzhu/EasyFlyTracker#2]
I am using Ausus windows 11, I extracted the zip file provided and edited the config file using spyder.But,when i tried to run the easyfly tracker it  showed pkl file doesnt exist.So,we created a pkl file in python and asigned it to be output folder.Even after assigning a pkl file it showed some problems with the codes as mentioned below.As i dont have computer science background i couldnt recognize the problem.Can you please help with this issue?
C:\Users\user> easyFlyTracker C:\EasyFlyTracker-master\EasyFlyTracker-master\tests
Traceback (most recent call last):
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\Scripts\easyFlyTracker-script.py", line 33, in <module>
    sys.exit(load_entry_point('easyFlyTracker==0.11.1', 'console_scripts', 'easyFlyTracker')())
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\easyFlyTracker\cli.py", line 22, in easyFlyTracker_
    params = __get_params()
  File "C:\Users\user\AppData\Local\Programs\Python\Python310\lib\site-packages\easyFlyTracker\src_code\utils.py", line 230, in __get_params
    with open(cfg_p, 'r', encoding='utf-8') as f:
PermissionError: [Errno 13] Permission denied: 'C:\\EasyFlyTracker-master\\EasyFlyTracker-master\\tests'

C:\Users\user>

**Comment by azzhu** [comment]
Permission denied. This is because the software does not have permission to read the configuration file. So do not store data and configuration files on drive C, and store them on other drives.

**Comment by jasmin1008** [comment]
Okay got it . thank you so much.

**Comment by azzhu** [comment]
Thank you! If you are interested can look at our website (http://easyflytracker.cibr.ac.cn/), welcome message feedback on BBS! - welcome.
