### ISSUE TITLE
opencv error

### ISSUE THREAD

**Issue by navinfreeze** [azzhu/EasyFlyTracker#9]
I am stuck with the error below while using the test data given in this repo

C:\Users\prabh>easyFlyTracker C:\Users\prabh\OneDrive\Desktop\tests\config.yaml
config params load from: C:\Users\prabh\OneDrive\Desktop\tests\output4/config.pkl
Please set the two points (A and B).
saved config params to: C:\Users\prabh\OneDrive\Desktop\tests\output4/config.pkl
Collect frames...Done
Calculate the background image...Done
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\prabh\AppData\Local\Programs\Python\Python311\Scripts\easyFlyTracker.exe\__main__.py", line 7, in <module>
  File "C:\Users\prabh\AppData\Local\Programs\Python\Python311\Lib\site-packages\easyFlyTracker\cli.py", line 50, in easyFlyTracker_
    f = FlySeg(**params_filter)
        ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prabh\AppData\Local\Programs\Python\Python311\Lib\site-packages\easyFlyTracker\src_code\fly_seg.py", line 123, in __init__
    self.comp_bg()
  File "C:\Users\prabh\AppData\Local\Programs\Python\Python311\Lib\site-packages\easyFlyTracker\src_code\fly_seg.py", line 277, in comp_bg
    bg = cv2.medianBlur(bg, 3)
         ^^^^^^^^^^^^^^^^^^^^^
cv2.error: OpenCV(4.8.0) D:/a/opencv-python/opencv-python/opencv/modules/imgproc/src/median_blur.simd.hpp:870: error: (-210:Unsupported format or combination of formats)  in function 'cv::opt_AVX2::medianBlur'

Can you please tell me where I might be going wrong?

**Comment by azzhu** [comment]
Hi, I have updated easyFlyTracker and fixed this problem, please upgrade easyFlyTracker to the latest version(0.14.1).
